style:
  backgroundColor: '#ffffff'
  fontFamily: '"Hiragino Sans", "Meiryo", sans-serif'
  fontSize: 16px
  padding: 20px
  maxWidth: 800px
  titleColor: '#333333'
  subtitleColor: '#666666'
bubbles:
  borderRadius: 18px
  padding: 12px 16px
  margin: 10px 0
  tailSize: 10px
  thinkStyle: dashed
  thinkBorderWidth: 2px
  shoutBorderRadius: 4px
characters:
  mercury:
    name: Mercury
    emoji: 🎧
    color: '#89CFF0'
    textColor: '#000000'
  glasses:
    name: Glasses
    emoji: 👓
    color: '#A0A0A0'
    textColor: '#FFFFFF'
  darkhair:
    name: Dark Hair
    emoji: 🖤
    color: '#36454F'
    textColor: '#FFFFFF'
  blonde:
    name: Blonde
    emoji: 💛
    color: '#FFD700'
    textColor: '#000000'
customCSS: ''
